#!/bin/sh
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=4:mem=20gb
#PBS -J 1982-2018

cd $HOME/git/PRISM-grids-into-FIPS-ZIP-USA/
module load anaconda3/personal
R --slave --args ${PBS_ARRAY_INDEX} < $HOME/git/PRISM-grids-into-FIPS-ZIP-USA/prog/02_grid_county_intersection/census_tract_wbgtmax.R

# to run type
# qsub -q med-bio census_tract_wbgtmax.run
# THIS WILL RUN ALL CHOSEN YEARS FOR PRISM PROCESSING
