#!/bin/sh
#PBS -l walltime=96:00:00
#PBS -l select=1:ncpus=4:mem=20gb
#PBS -J 2010-2058

cd $HOME/git/PRISM-grids-into-FIPS-ZIP-censustract-USA/
module load anaconda3/personal
R --slave --args ${PBS_ARRAY_INDEX} < $HOME/git/PRISM-grids-into-FIPS-ZIP-censustract-USA/prog/02_grid_county_intersection/census_tract_ppt.R

# to run type
# qsub -q med-bio census_tract_ppt.run
# THIS WILL RUN ALL CHOSEN ARGUMENTS FOR PRISM PROCESSING
