#!/bin/sh
#PBS -l walltime=168:00:00
#PBS -l select=1:ncpus=4:mem=20gb
#PBS -J 1982-1982

cd $HOME/git/PRISM-grids-into-political-entities-USA/
module load anaconda3/personal
R --slave --args ${PBS_ARRAY_INDEX} < $HOME/git/PRISM-grids-into-political-entities-USA/prog/02_grid_county_intersection/grid_county_intersection_raster_prism_cx1.R

# to run type
# qsub -q med-bio medbio_run.run
# THIS WILL RUN ALL CHOSEN YEARS FOR PRISM PROCESSING