#!/bin/sh
#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=4:mem=20gb
#PBS -J 1981-1982

cd $HOME/git/PRISM-grids-into-FIPS-ZIP-censustract-USA/
module load anaconda3/personal
R --slave --args ${PBS_ARRAY_INDEX} < $HOME/git/PRISM-grids-into-FIPS-ZIP-censustract-USA/prog/02_grid_county_intersection/fips_wbgtmax.R

# to run type
# qsub -q med-bio fips_wbgtmax.run
# THIS WILL RUN ALL CHOSEN ARGUMENTS FOR PRISM PROCESSING
